version: '3'
services:
  practice-spa:
    container_name: practice-spa
    build:
      context: .
      dockerfile: Dockerfile
      #args:
      # - REACT_APP_BASE_PATH=http://${SPA_PUBLIC_IP}
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=http://localhost:4001
